# Generated by Django 4.2.5 on 2023-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.CharField(choices=[('1,', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], default='1', max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
